# -*- coding: utf-8 -*-
"""3107서소영 - 데이터분석-이름.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RtuJIZZtb2_mkBdt6I0kQcmNfH8PD0Y

### **범죄 발생 데이터 분석**
"""

from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt
import pandas as pd

data_weekday_crime = pd.read_csv('경찰청_범죄 발생 시간대 및 요일_20191231.csv', encoding='cp949')

weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
weekday_data = data_weekday_crime[weekdays]

total_crimes_per_weekday = weekday_data.sum()

fig, ax = plt.subplots(figsize=(10, 6))
total_crimes_per_weekday.plot(kind='bar', color='skyblue', ax=ax)
ax.set_title('Weekday-wise Crime Occurrence Rates', fontsize=14)
ax.set_xlabel('Weekday', fontsize=12)
ax.set_ylabel('Total Crimes', fontsize=12)
plt.xticks(rotation=0)
plt.grid(visible=True, which='both', linestyle='--', linewidth=0.5)
plt.tight_layout()
plt.show()

time_slots = ['0:00-02:59', '03:00-05:59', '06:00-08:59', '09:00-11:59',
              '12:00-14:59', '15:00-17:59', '18:00-20:59', '21:00-23:59']
time_data = data_weekday_crime[time_slots]

total_crimes_per_time_slot = time_data.sum()

fig, ax = plt.subplots(figsize=(12, 6))
total_crimes_per_time_slot.plot(kind='bar', color='coral', ax=ax)
ax.set_title('Time-wise Crime Occurrence Rates', fontsize=14)
ax.set_xlabel('Time Slot', fontsize=12)
ax.set_ylabel('Total Crimes', fontsize=12)
plt.xticks(rotation=45)
plt.grid(visible=True, which='both', linestyle='--', linewidth=0.5)
plt.tight_layout()
plt.show()

data_cyber_crime = pd.read_csv('경찰청_연도별 사이버 범죄 통계 현황_08_31_2020.csv', encoding='cp949')

cyber_crime_years = data_cyber_crime['연도'].unique()
total_cyber_crimes_per_year = data_cyber_crime[data_cyber_crime['구분'] == '발생건수'].drop(columns=['연도', '구분']).sum(axis=1)

fig, ax = plt.subplots(figsize=(8, 5))
total_cyber_crimes_per_year.plot(kind='line', marker='o', color='purple', ax=ax)
ax.set_xticks(range(len(cyber_crime_years)))
ax.set_xticklabels(cyber_crime_years, rotation=0)
ax.set_title('Year-wise Cyber Crime Occurrence Rates', fontsize=14)
ax.set_xlabel('Year', fontsize=12)
ax.set_ylabel('Total Cyber Crimes', fontsize=12)
plt.grid(visible=True, which='both', linestyle='--', linewidth=0.5)
plt.tight_layout()
plt.show()

data_area_crime = pd.read_csv('경찰청_범죄 발생 지역별 통계_20221231 - 복사본.csv', encoding='cp949')

major_regions = ['Seoul', 'Busan', 'Daegu', 'Incheon', 'Gwangju', 'Daejeon', 'Ulsan', 'Sejong', 'Gyeonggi']
region_crime_totals = data_area_crime[major_regions].sum()

fig, ax = plt.subplots(figsize=(10, 6))
region_crime_totals.plot(kind='bar', color='green', ax=ax)
ax.set_title('Region-wise Crime Occurrence Rates', fontsize=14)
ax.set_xlabel('Region', fontsize=12)
ax.set_ylabel('Total Crimes', fontsize=12)
plt.xticks(rotation=0)
plt.grid(visible=True, which='both', linestyle='--', linewidth=0.5)

import seaborn as sns
time_weekday_data = data_weekday_crime.set_index('범죄중분류')[time_slots + weekdays]

total_crimes = time_weekday_data.sum().sum()

normalized_time_weekday_data = time_weekday_data / total_crimes

time_day_matrix = normalized_time_weekday_data.groupby(normalized_time_weekday_data.index)[time_slots + weekdays].mean()

plt.figure(figsize=(14, 8))
sns.heatmap(time_day_matrix, annot=True, cmap='coolwarm', fmt=".2%", cbar_kws={'label': 'Percentage of Total Crimes'})
plt.title('Crime Occurrence by Time and Weekday', fontsize=16)
plt.ylabel('Crime Type', fontsize=12)
plt.xlabel('Time/Day', fontsize=12)
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.show()

